# Generated by Django 4.2.3 on 2023-09-07 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confirme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_trans', models.CharField(max_length=80)),
                ('trans_id', models.CharField(max_length=150)),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
            },
        ),
        migrations.CreateModel(
            name='Heure_d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Valide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numticket', models.CharField(max_length=80)),
                ('numchaise', models.CharField(blank=True, max_length=80, null=True)),
                ('confirmation', models.ManyToManyField(to='angaapp.confirme')),
            ],
        ),
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=80)),
                ('img', models.ImageField(upload_to='societe_images/')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='angaapp.destination')),
            ],
            options={
                'verbose_name_plural': 'Societe',
            },
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_reservation', models.CharField(editable=False, max_length=100, unique=True)),
                ('nom', models.CharField(blank=True, max_length=80)),
                ('prenom', models.CharField(blank=True, max_length=80)),
                ('date', models.DateField()),
                ('tel', models.CharField(blank=True, max_length=80)),
                ('num_trans', models.CharField(blank=True, max_length=80)),
                ('confirm', models.BooleanField(default=False)),
                ('val', models.BooleanField(default=False)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='angaapp.destination')),
                ('societe', models.ManyToManyField(to='angaapp.societe')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='angaapp.heure_d')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'db_table': 'reservations',
                'ordering': ['-create_date'],
            },
        ),
        migrations.AddField(
            model_name='confirme',
            name='reservation',
            field=models.ManyToManyField(to='angaapp.reservations'),
        ),
    ]
