# Generated by Django 4.2.3 on 2023-08-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='val',
            field=models.BooleanField(default=False),
        ),
    ]
