# Generated by Django 4.2.3 on 2024-03-11 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('angaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirme',
            name='montant_paye',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='angaapp.depart'),
        ),
    ]
