# Generated by Django 4.2.3 on 2023-09-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angaapp', '0002_reservations_mode_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societe',
            name='img',
            field=models.FileField(upload_to='societe_images/'),
        ),
    ]
