# Generated by Django 4.2.3 on 2024-03-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angaapp', '0002_alter_confirme_montant_paye'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='car',
            field=models.CharField(choices=[('VIP', 'VIP'), ('Standard', 'Standard')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
