# Generated by Django 4.2.3 on 2023-08-21 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angaapp', '0002_reservations_val'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservations',
            options={'ordering': ['-create_date'], 'verbose_name': 'Reservation', 'verbose_name_plural': 'Reservations'},
        ),
        migrations.AlterModelTable(
            name='reservations',
            table='reservations',
        ),
    ]
