# Generated by Django 4.2.3 on 2023-08-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angaapp', '0003_alter_reservations_options_alter_reservations_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societe',
            name='img',
            field=models.ImageField(upload_to='societe_images/'),
        ),
    ]
