# Generated by Django 4.2.3 on 2023-09-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angaapp', '0004_alter_societe_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societe',
            name='img',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
