# Generated by Django 4.2.3 on 2024-01-31 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('angaapp', '0009_rename_contenu_sms_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heure_d',
            name='societe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='angaapp.societe'),
            preserve_default=False,
        ),
    ]
