# Generated by Django 4.2.3 on 2024-01-31 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angaapp', '0011_heure_d_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heure_d',
            name='destination',
        ),
    ]
