# Generated by Django 4.2.3 on 2024-02-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angaapp', '0014_heure_d_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='datedl_cnib',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='reservations',
            name='numero_cnib',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='tel',
            field=models.CharField(blank=True, max_length=80, unique=True),
        ),
    ]
