# Generated by Django 4.2.3 on 2024-02-03 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angaapp', '0017_remove_heure_d_destination_kartie_heure_d_kartie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heure_d',
            name='kartie',
        ),
        migrations.DeleteModel(
            name='Kartie',
        ),
    ]
