# Generated by Django 4.2.3 on 2024-02-03 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('angaapp', '0018_remove_heure_d_kartie_delete_kartie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kartie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=80)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='angaapp.destination')),
            ],
        ),
        migrations.AddField(
            model_name='heure_d',
            name='kartie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='angaapp.kartie'),
            preserve_default=False,
        ),
    ]
