# Generated by Django 4.2.3 on 2024-02-03 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('angaapp', '0019_kartie_heure_d_kartie'),
    ]

    operations = [
        migrations.AddField(
            model_name='heure_d',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='angaapp.destination'),
            preserve_default=False,
        ),
    ]
